version: '2'
services:
  postgresql:
    image: postgres:9
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=dbname
    ports:
      - 15432:5432

  run:
    depends_on:
      - postgresql
    build: .
    links:
      - postgresql:postgresql.local
    environment:
      - SERVICE_NAME=docker-learning
      - NODE_ENV=production
      - POSTGRESQL_HOST=postgresql.local
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=admin
      - POSTGRESQL_PASSWORD=12345
      - POSTGRESQL_NAME=dbname
      - PORT=80
    ports:
      - "9000:80"
    command: >
      /bin/sh -c "
        set -e
        dockerize -wait tcp://$$POSTGRESQL_HOST:$$POSTGRESQL_PORT
        npm --silent start
      "
